### ISSUE TITLE
Upgrade to GeoNode 4

### ISSUE THREAD

**Issue by giohappy** [geosolutions-it/UNMISS-GeoStory#54]
```[tasklist]
### Tasks
- [ ] https://github.com/geosolutions-it/UNMISS-GeoStory/issues/55
- [ ] https://github.com/geosolutions-it/UNMISS-GeoStory/issues/56
- [ ] https://github.com/geosolutions-it/UNMISS-GeoStory/issues/57
- [ ] https://github.com/geosolutions-it/UNMISS-GeoStory/issues/58
- [ ] https://github.com/geosolutions-it/UNMISS-GeoStory/issues/59
```

**Comment by giohappy** [comment]
Documentation of the upgrade is available [here](https://docs.google.com/document/d/1-npxdxzsYHdr7RBzd6jj0v5RrsQU6dg0/edit#heading=h.i51my5xdykhw).

Updated deployment documentation (for them) is available [here](https://docs.google.com/document/d/1Jtx_sLYbhwR0ptWUeVRFecb39xS2gnYF4TtLhsji3Zw)
